module.exports = {
    add_category_button_add: 'Add?',
    add_category_error: 'Error in adding category',
    add_category_label: 'New Category?',
    add_parameter_button_add: 'Add',
    add_parameter_error: 'Error in adding category',
    add_parameter_label_label: 'Label',
    add_parameter_label_name: 'Name',
    add_parameter_label_type: 'Type',
    change_paramCategory_chose_busy: 'Wait until the previous request processed..',
    close: 'Close',
    installer_header_title: 'Paraman Installer',
    installer_step_createDB_action:`Create`,
    installer_step_createDB_done: 'Database created successfully',
    installer_step_createDB_response_done: 'database file: %s',
    installer_step_createDB_response_error: `Error! check the console to see error details`,
    installer_step_createDB_response_status_error: 'There is an error creating the database',
    installer_step_createDB_text: `Create the sqlite database file. the file will be created in:\r\n`,
    installer_step_createDB_title: 'Create the database!',
    installer_step_migrate_actionText: `Migrate`,
    installer_step_migrate_response_done: 'Database migrated successfully',
    installer_step_migrate_response_error: `Error! check the console to see error details`,
    installer_step_migrate_response_status_error: 'There is an error migrating the database',
    installer_step_migrate_text: `run 'php artisan migrate' to migrate the database, the migrations on the queue:\r\n`,
    installer_step_migrate_title: `Migrate the database!`,
    installer_step_refresh_action:'Refresh',
    installer_step_refresh_text:'Refresh and start using Paraman!',
    installer_step_refresh_title: 'Go !',
    save_changes: 'Save Changes',
    save: 'Save',
    parameter_header_unsaved_changes: 'Unsaved Changes!',
    parameter_meta_button_revisions: 'Revisions',
    parameter_meta_log_date: 'Date',
    parameter_meta_log_field: 'Field',
    parameter_meta_log_old: 'Old',
    parameter_meta_log_new: 'New',
    parameter_meta_log_diff: 'Diff',
    parameter_meta_button_category: 'Category',
    parameter_meta_humanized_updatedAt: 'updated',
    parameter_response_error: 'Error in updating parameter (%s)',
    parameter_changed: 'Parameter: %s has been updated successfully',
    parameters_list_not_found: 'No Parameters Added, start by adding one',
}