// A theme is also required
require('tinymce/themes/modern/theme')

// Any plugins you want to use has to be imported
require('tinymce/plugins/advlist')
require('tinymce/plugins/anchor')
require('tinymce/plugins/autolink')
require('tinymce/plugins/charmap')
require('tinymce/plugins/code')
require('tinymce/plugins/codesample')
require('tinymce/plugins/colorpicker')
require('tinymce/plugins/contextmenu')
require('tinymce/plugins/directionality')
require('tinymce/plugins/emoticons')
require('tinymce/plugins/fullscreen')
require('tinymce/plugins/help')
require('tinymce/plugins/hr')
require('tinymce/plugins/image')
require('tinymce/plugins/imagetools')
require('tinymce/plugins/insertdatetime')
require('tinymce/plugins/link')
require('tinymce/plugins/lists')
require('tinymce/plugins/media')
require('tinymce/plugins/nonbreaking')
require('tinymce/plugins/pagebreak')
require('tinymce/plugins/paste')
require('tinymce/plugins/preview')
require('tinymce/plugins/print')
require('tinymce/plugins/save')
require('tinymce/plugins/searchreplace')
require('tinymce/plugins/table')
require('tinymce/plugins/template')
require('tinymce/plugins/textcolor')
require('tinymce/plugins/textpattern')
require('tinymce/plugins/toc')
require('tinymce/plugins/visualblocks')
require('tinymce/plugins/visualchars')
require('tinymce/plugins/wordcount')
